### PR TITLE
new upstream v3.9.3

### PR DESCRIPTION
**Pull request by joelkraehemann**
* fixed SIGSEGV with AgsPitchSampler

### CODE REVIEW

**Comment by joelkraehemann** [comment]
,bot build

**Comment by joelkraehemann** [comment]
,build

**Comment by joelkraehemann** [comment]
,bot build

**Comment by joelkraehemann** [comment]
,build

**Comment by joelkraehemann** [comment]
,bot build

**Comment by joelkraehemann** [comment]
,buildbot build

**Comment by hfiguiere** [comment]
bot, build

**Comment by joelkraehemann** [comment]
thank you!

**Pull request merged**
