### PR TITLE
Update to GNOME 45

### PR DESCRIPTION
**Pull request by hfiguiere**
- remove unused bits in the manifest

### CODE REVIEW

**Comment by hfiguiere** [comment]
ah yeah vst3sdk needs fixing. again.

**Comment by joelkraehemann** [comment]
hi @hfiguiere what's up?

**Comment by hfiguiere** [comment]
I haven't tried the build yet.

**Comment by joelkraehemann** [comment]
@hfiguiere you should update to latest gsequencer.

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
seems to work.

**Comment by hfiguiere** [comment]
I can merge this if you don't have time.

**Pull request merged**
