### PR TITLE
new upstream v3.6.14

### PR DESCRIPTION
**Pull request by joelkraehemann**
* fixed AgsPlayback cleanup

### CODE REVIEW

**Comment by joelkraehemann** [comment]
bot, build

**Comment by joelkraehemann** [comment]
bot, build

**Comment by joelkraehemann** [comment]
bot, build

**Comment by barthalion** [comment]
@joelkraehemann Answering your IRC question, it seems there's some silent corruption happening on x86 builders. I'm trying to find a fix since few days.

**Comment by barthalion** [comment]
I will retrigger failed builds as usually.

**Comment by barthalion** [comment]
bot, build

**Pull request merged**
